In [40]:
import numpy as np

class NeuralNetwork:
    # how will the weights come inside 
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))

    def forward_pass(self,x,initial_weights,initial_bias):
        z =  x@initial_weights.T  + initial_bias
        self.result = self.sigmoid(z)
        return self.result 
    
    def grad_w(self,y_pred,label,x):
        return self.grad_b(y_pred,label,x)*x
        
    def grad_b(self,y_pred,label,x):
        #return 2*(label.T-y_pred)@self.sigmoid(x).T@(1-self.sigmoid(x))
        return 2*(label.T-y_pred)*self.result*(1-self.result)

    def gradient_descent(self,features,initial_weights,initial_bias,epochs,learning_rate,labels):
        updated_weights = initial_weights.copy()
        updated_bias  = initial_bias
        
        for _ in range(epochs):
            for x in features:
                y_pred = self.forward_pass(x,initial_weights,initial_bias)
                grad_w=self.grad_w(y_pred,labels,x)
                grad_b = self.grad_b(y_pred,labels,x)* 1.0
                
                updated_weights =  updated_weights - learning_rate * grad_w # what is a safer value to initialize for grad_w?
                updated_bias =  updated_bias - learning_rate * grad_b # what is a safer value to initialize for grad_b?
        return updated_weights,updated_bias
                
    
    
def train_neuron(features: np.ndarray, labels: np.ndarray, initial_weights: np.ndarray, initial_bias: float, learning_rate: float, epochs: int) -> (np.ndarray, float, list[float]):
	# Your code here
    labels = np.array([labels])
    initial_weights=np.array([initial_weights])
    features = np.array(features)
    print(features.shape)
    print(labels.shape)
    print(initial_weights.shape)
    neural_net = NeuralNetwork()
    result = neural_net.forward_pass(features,initial_weights,initial_bias)
    print(result)
    updated_weights,updated_bias=neural_net.gradient_descent(features,initial_weights,initial_bias,epochs,learning_rate,labels)
    return updated_weights, updated_bias





In [31]:
#features =np.array([[1.0, 2.0], [2.0, 1.0], [-1.0, -2.0]]); labels = np.array([[1, 0, 0]]); initial_weights = np.array([[0.1, -0.2]]); initial_bias = 0.0; learning_rate = 0.1; epochs = 2
features = [[1.0, 2.0], [2.0, 1.0], [-1.0, -2.0]]; labels = [1, 0, 0]; initial_weights = [0.1, -0.2]; initial_bias = 0.0; learning_rate = 0.1;epochs = 2

In [41]:
train_neuron(features,labels,initial_weights,initial_bias,learning_rate,epochs)

(3, 2)
(1, 3)
(1, 2)
[[0.42555748]
 [0.5       ]
 [0.57444252]]


(array([[-0.01455847, -0.27911695],
        [ 0.18544153, -0.17911695],
        [ 0.18544153, -0.17911695]]),
 array([[-0.14778332],
        [ 0.14778332],
        [ 0.14778332]]))

In [ ]:
import numpy as np

class NeuralNetwork:
    # how will the weights come inside 
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))

    def forward_pass(self,x,initial_weights,initial_bias):
        z =  x@initial_weights  + initial_bias
        self.result = self.sigmoid(z)
        return self.result 
    
    def grad_w(self,y_pred,label,x):
        return x.T@self.grad_b(y_pred,label)
        
    def grad_b(self,y_pred,label):
        n = len(label)
        #return 2*(label.T-y_pred)@self.sigmoid(x).T@(1-self.sigmoid(x))
        return (2/n)*(y_pred-label)*y_pred*(1-y_pred)

    # def gradient_descent(self,features,initial_weights,initial_bias,epochs,learning_rate,labels):
    #     updated_weights = initial_weights.copy()
    #     updated_bias  = initial_bias
    #     mse_list=[]
        
        
    #     for _ in range(epochs):
    #         for j,x in enumerate(features):
    #             #x =x.reshape(1,-1)
    #             y_true = labels[j]
    #             y_pred = self.forward_pass(x,updated_weights,updated_bias)
    #             grad_w=self.grad_w(y_pred,y_true,x)
    #             grad_b = self.grad_b(y_pred,y_true)
                
    #             updated_weights =  updated_weights - learning_rate * grad_w # what is a safer value to initialize for grad_w?
    #             updated_bias =  updated_bias - learning_rate * grad_b # what is a safer value to initialize for grad_b?
                
    #         mse_list.append(np.square(y_pred-labels).mean())
    #     return updated_weights,updated_bias,mse_list
                
    def batch_gradient_descent(self,features,initial_weights,initial_bias,epochs,learning_rate,labels):
        updated_weights = initial_weights.copy()
        updated_bias  = initial_bias
        mse_list=[]
        
        for _ in range(epochs):
            #for j,x in enumerate(features):
                #x =x.reshape(1,-1)
            #y_true = labels[j]
            y_pred = self.forward_pass(features,updated_weights,updated_bias)
            grad_w=self.grad_w(y_pred,labels,features)
            grad_b = np.sum(self.grad_b(y_pred,labels))
            
            updated_weights =  updated_weights - learning_rate * grad_w # what is a safer value to initialize for grad_w?
            updated_bias =  updated_bias - learning_rate * grad_b # what is a safer value to initialize for grad_b?
                
            mse_list.append(np.square(y_pred-labels).mean())
        return updated_weights,updated_bias,mse_list
    
    
def train_neuron(features: np.ndarray, labels: np.ndarray, initial_weights: np.ndarray, initial_bias: float, learning_rate: float, epochs: int) -> (np.ndarray, float, list[float]):
	# Your code here
    #labels = np.array([labels])
    #initial_weights=np.array([initial_weights])
    #features = np.array(features)
    neural_net = NeuralNetwork()
    result = neural_net.forward_pass(features,initial_weights,initial_bias)
    #print(result)
    updated_weights,updated_bias,mse=neural_net.batch_gradient_descent(features,initial_weights,initial_bias,epochs,learning_rate,labels)
    mse_value = np.round(mse,4)
    updated_weights=  np.round(updated_weights,4)
    return updated_weights.tolist(), np.round(updated_bias,4).tolist(), mse_value.tolist()


print(train_neuron(np.array([[1.0, 2.0], [2.0, 1.0], [-1.0, -2.0]]), np.array([1, 0, 0]), np.array([0.1, -0.2]), 0.0, 0.1, 2))


([0.1036, -0.1425], -0.0167, array([0.3033, 0.2942]))


In [81]:
print(train_neuron(np.array([[1.0, 2.0], [2.0, 1.0], [-1.0, -2.0]]), np.array([1, 0, 0]), np.array([0.1, -0.2]), 0.0, 0.1, 2))

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [ ]:
import torch
from typing import List, Tuple, Union


def train_neuron(
    features: Union[List[List[float]], torch.Tensor],
    labels:   Union[List[float],      torch.Tensor],
    initial_weights: Union[List[float], torch.Tensor],
    initial_bias: float,
    learning_rate: float,
    epochs: int
) -> Tuple[List[float], float, List[float]]:
    """
    Train a single neuron (sigmoid activation) with mean-squared-error loss.

    Returns (updated_weights, updated_bias, mse_per_epoch)
    — weights & bias are rounded to 4 decimals; each MSE value is rounded too.
    """
    # Your implementation here
    pass

In [51]:
ar=np.array([0.1, -0.2])
print(ar.shape)
print(ar.reshape(2,1))

(2,)
[[ 0.1]
 [-0.2]]
